
project_id = "kysvcexqmywyrawakwfs"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[functions]
[functions.product-stock]
verify_jwt = false
[functions.submit-inquiry]
verify_jwt = false

[realtime]
enabled = true

[storage]
enabled = true
