print("Mobile Responsiveness Testing Tool")
print("=================================\n")
print("Options:")
print("1. Test StockInWizard mobile view")
print("2. Test TransferHistoryTable mobile view")
print("3. Test StockInStepReview mobile view")
print("4. Test StockInStepBatches mobile view")
print("5. Test StockInStepFinalize mobile view")
print("stop - Exit the testing tool\n")

user_input = input("Enter your choice: ")