// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Temporary minimal version to get the app running
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://placeholder.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || 'placeholder_key';

// Create a basic client without type checking for now
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
